name: Keep Alive

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl https://footystats-proxy.onrender.com/cache-status
